import fs from "node:fs";
import path from "node:path";

// Bootstrap a remote machine into a usable tdsp node WITHOUT assuming anything
// about how it provides node. `ssh host "cmd"` runs a non-interactive, non-login
// shell with a stripped environment, and machines vary wildly: nvm is a shell
// function that rc files often skip non-interactively, fnm/volta/asdf each
// initialize differently, others put node straight on PATH. So we DON'T assume —
// we empirically try a ladder of strategies until one actually resolves `node`,
// verify it, and generate a self-discovering wrapper that retries the same ladder
// at runtime (so it survives later version-manager drift). A manual override is
// always tried first, and an honest failure beats a silently-broken install.

// One rung of the discovery ladder: a name and the shell snippet that tries to
// make `node` available. The snippets are shared by discovery (verify a rung
// works now) and the generated wrapper (retry the rungs at runtime).
export interface NodeStrategy {
  name: string;
  setup: string;
}

export const NODE_RUNGS: NodeStrategy[] = [
  // already on the bare PATH (system / brew / volta shims often are) — empty setup
  { name: "path", setup: "" },
  // fnm: reachable as a binary even non-interactively (e.g. /opt/homebrew/bin/fnm)
  { name: "fnm", setup: `command -v fnm >/dev/null 2>&1 && { eval "$(fnm env 2>/dev/null)"; fnm use default >/dev/null 2>&1; }` },
  // nvm: source its script directly (the rc-guarded function won't load for us)
  { name: "nvm", setup: `[ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1` },
  // last resort: throw the usual shim/bin dirs onto PATH and hope one has node
  { name: "common", setup: `export PATH="$HOME/.volta/bin:$HOME/.asdf/shims:/opt/homebrew/bin:/usr/local/bin:/usr/bin:$PATH"` },
];

// Runs a shell snippet ON the target machine, reporting success + stdout. In prod
// this wraps `ssh target sh -c <script>` (or RemoteRunner.exec); tests inject a fake.
export type Probe = (script: string) => Promise<{ ok: boolean; stdout: string }>;

export interface DiscoverResult {
  ok: boolean;
  strategy?: string; // which rung resolved node
  version?: string; // `node -v` output, for the operator's log
}

/**
 * Find the first ladder rung that actually resolves a working node on the target.
 * A manual override (a user-supplied setup snippet) is tried first. Returns which
 * rung won + the node version, or ok:false when NOTHING works (never guesses).
 */
export async function discoverNode(probe: Probe, override?: string): Promise<DiscoverResult> {
  const rungs = override ? [{ name: "override", setup: override }, ...NODE_RUNGS] : NODE_RUNGS;
  for (const rung of rungs) {
    const script = `${rung.setup}\ncommand -v node >/dev/null 2>&1 && node -v`;
    const res = await probe(script);
    if (res.ok) return { ok: true, strategy: rung.name, version: res.stdout.trim() || undefined };
  }
  return { ok: false };
}

export interface WrapperOpts {
  appDir: string; // where the app (source + node_modules) lives on the target
  override?: string; // optional user-specified node setup, tried before the auto rungs
}

/** POSIX single-quote a string for embedding in the generated shell script. */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * The node-discovery ladder as a runnable shell snippet: each non-"path" rung is a
 * guarded fallback (only runs if node isn't found yet), override first. Shared by
 * the generated wrapper AND by bootstrap's `npm install` step, so install-time and
 * run-time resolve node identically.
 */
export function nodeLadderScript(override?: string): string {
  const auto = NODE_RUNGS.filter((r) => r.name !== "path");
  const rungs = override ? [{ name: "override", setup: override }, ...auto] : auto;
  return rungs.map((r) => `command -v node >/dev/null 2>&1 || { ${r.setup}; }`).join("\n");
}

/**
 * Generate the `tdsp` launcher for a target. It's self-discovering: every call it
 * walks the same ladder (override first, then fnm/nvm/common) until node resolves,
 * ensures git/tmux are on PATH, then execs the app passing args through. If no rung
 * works it exits 127 with a clear message instead of a cryptic command-not-found.
 */
export function renderWrapper(opts: WrapperOpts): string {
  const app = shq(opts.appDir);
  const ladder = nodeLadderScript(opts.override);
  return `#!/bin/sh
# tdsp launcher — generated by switchyard bootstrap. Finds a working node across
# heterogeneous machines (the non-interactive ssh PATH rarely has it), then runs
# the app. Self-discovering: retries the ladder each call, so it survives node
# version-manager changes without re-bootstrapping.
APP=${app}
${ladder}
# git/tmux for what the app actually does
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
command -v node >/dev/null 2>&1 || { echo "tdsp: no usable node found on this machine" >&2; exit 127; }
exec node "$APP/node_modules/.bin/tsx" "$APP/server/tdsp.ts" "$@"
`;
}

// ---------- symmetric local install (`tdsp install`) ----------
// One model for EVERY machine: a single canonical code pointer at
// ~/.task-dispatcher/src (a real clone, or a symlink to the clone you already
// have), plus a global `tdsp` wrapper that always execs <src>/server/tdsp.ts. The
// machine you sit at and the machine A reaches over ssh run the exact same setup —
// no second copy, no drift.
export interface InstallPlan {
  src: string; // canonical code pointer: <home>/.task-dispatcher/src
  binDir: string;
  binPath: string; // the wrapper A invokes over ssh: <home>/.task-dispatcher/bin/tdsp
  localBin: string; // a convenience symlink onto PATH for interactive use
  wrapper: string; // wrapper content (execs $src/server/tdsp.ts)
}

/** Compute the canonical install paths + wrapper for a machine, given the clone
 *  we're installing from. Pure — the fs work is applyInstall. */
export function installPlan(home: string, _cloneDir: string): InstallPlan {
  const root = path.join(home, ".task-dispatcher");
  const src = path.join(root, "src");
  const binDir = path.join(root, "bin");
  return {
    src,
    binDir,
    binPath: path.join(binDir, "tdsp"),
    localBin: path.join(home, ".local", "bin", "tdsp"),
    wrapper: renderWrapper({ appDir: src }), // always points at the src pointer
  };
}

/** Force-create a symlink target→linkPath (replacing whatever's there). */
function relink(target: string, linkPath: string) {
  fs.mkdirSync(path.dirname(linkPath), { recursive: true });
  try { fs.rmSync(linkPath, { recursive: true, force: true }); } catch { /* nothing there */ }
  fs.symlinkSync(target, linkPath);
}

/**
 * Set up THIS machine's canonical install from a clone: point src at the clone
 * (unless the clone already IS src), write the wrapper, and link it onto PATH at
 * ~/.local/bin/tdsp (best-effort). Idempotent. Run by `tdsp install` and by the
 * remote bootstrap once the code is in place.
 */
export function applyInstall(home: string, cloneDir: string): InstallPlan {
  const p = installPlan(home, cloneDir);
  fs.mkdirSync(p.binDir, { recursive: true });
  // src → cloneDir (skip if the clone already lives at src — a fresh `git clone <src>`)
  if (path.resolve(cloneDir) !== path.resolve(p.src)) relink(path.resolve(cloneDir), p.src);
  fs.writeFileSync(p.binPath, p.wrapper, { mode: 0o755 });
  try { relink(p.binPath, p.localBin); } catch { /* ~/.local/bin not writable — fixed path still works */ }
  return p;
}

// ---------- one-click remote install (the A-side button) ----------
// Set up tdsp on a remote machine over ssh in one shot — the convenient path for a
// machine you DON'T want to walk over to. `run` executes a shell script on the
// target (ssh ... sh -s, stdin-fed, so the remote shell can't eat `$(fnm env)`).
export interface BootstrapDeps {
  home: string; // the target's home dir (absolute)
  originUrl: string; // the repo to clone if the target has no code yet
  run(script: string): Promise<{ ok: boolean; stdout: string }>;
  override?: string; // optional manual node setup, tried first everywhere
}

export interface BootstrapResult {
  ok: boolean;
  srcDir?: string;
  binPath?: string;
  strategy?: string;
  nodeVersion?: string;
  cloned?: boolean; // true: cloned fresh; false: reused the target's existing src
  error?: string;
}

/**
 * Install tdsp on a machine over ssh and return the verified wrapper path (recorded
 * as the host's tdsp_bin). One canonical pointer — ~/.task-dispatcher/src — + a
 * wrapper pointing at it. Fail-fast:
 *   1. discover a working node — abort before touching the machine if none.
 *   2. ensure code at src: REUSE an existing src untouched (never pull — a symlink
 *      may point at a clone whose live instance would reload); clone fresh only when
 *      src is absent.
 *   3. npm install in src only when node_modules is missing.
 *   4. write the self-discovering wrapper at ~/.task-dispatcher/bin/tdsp → src.
 *   5. verify it runs (`tdsp list`).
 *   6. remove the legacy ~/.task-dispatcher/app copy (pre-src model), best-effort.
 * Node is NEVER reinstalled — only the app's own node_modules.
 */
export async function bootstrapMachine(deps: BootstrapDeps): Promise<BootstrapResult> {
  const root = `${deps.home}/.task-dispatcher`;
  const src = `${root}/src`;
  const binPath = `${root}/bin/tdsp`;
  const ladder = nodeLadderScript(deps.override);

  const found = await discoverNode(deps.run, deps.override);
  if (!found.ok) return { ok: false, error: "no usable node found on the target machine" };

  // reuse an existing src as-is; clone only when absent (REUSED / CLONED in output)
  const ensure = await deps.run(
    `if [ -e ${shq(src)} ]; then echo REUSED; else mkdir -p ${shq(root)} && git clone ${shq(deps.originUrl)} ${shq(src)} && echo CLONED; fi; ` +
      `[ -e ${shq(src)}/server/tdsp.ts ] && echo HAVECODE`,
  );
  if (!ensure.ok || !/HAVECODE/.test(ensure.stdout)) {
    return { ok: false, error: "couldn't get the code onto the target — check its git access, or run `tdsp install` there" };
  }
  const cloned = /CLONED/.test(ensure.stdout);

  const inst = await deps.run(`${ladder}\ncd ${shq(src)} && [ -d node_modules ] || npm install --no-audit --no-fund`);
  if (!inst.ok) return { ok: false, error: "npm install failed on the target" };

  const wrapper = renderWrapper({ appDir: src, override: deps.override });
  const b64 = Buffer.from(wrapper).toString("base64");
  const write = await deps.run(`mkdir -p ${shq(`${root}/bin`)} && printf %s ${shq(b64)} | base64 --decode > ${shq(binPath)} && chmod +x ${shq(binPath)} && echo OK`);
  if (!write.ok) return { ok: false, error: "could not install the wrapper" };

  const verify = await deps.run(`${shq(binPath)} list >/dev/null 2>&1 && echo OK`);
  if (!verify.ok) return { ok: false, error: "the installed wrapper failed to run" };

  await deps.run(`rm -rf ${shq(`${root}/app`)}`); // drop the legacy separate copy

  return { ok: true, srcDir: src, binPath, strategy: found.strategy, nodeVersion: found.version, cloned };
}
