// Bootstrap a remote machine into a usable tdsp node WITHOUT assuming anything
// about how it provides node. `ssh host "cmd"` runs a non-interactive, non-login
// shell with a stripped environment, and machines vary wildly: nvm is a shell
// function that rc files often skip non-interactively, fnm/volta/asdf each
// initialize differently, others put node straight on PATH. So we DON'T assume —
// we empirically try a ladder of strategies until one actually resolves `node`,
// verify it, and generate a self-discovering wrapper that retries the same ladder
// at runtime (so it survives later version-manager drift). A manual override is
// always tried first, and an honest failure beats a silently-broken install.

// One rung of the discovery ladder: a name and the shell snippet that tries to
// make `node` available. The snippets are shared by discovery (verify a rung
// works now) and the generated wrapper (retry the rungs at runtime).
export interface NodeStrategy {
  name: string;
  setup: string;
}

export const NODE_RUNGS: NodeStrategy[] = [
  // already on the bare PATH (system / brew / volta shims often are) — empty setup
  { name: "path", setup: "" },
  // fnm: reachable as a binary even non-interactively (e.g. /opt/homebrew/bin/fnm)
  { name: "fnm", setup: `command -v fnm >/dev/null 2>&1 && { eval "$(fnm env 2>/dev/null)"; fnm use default >/dev/null 2>&1; }` },
  // nvm: source its script directly (the rc-guarded function won't load for us)
  { name: "nvm", setup: `[ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1` },
  // last resort: throw the usual shim/bin dirs onto PATH and hope one has node
  { name: "common", setup: `export PATH="$HOME/.volta/bin:$HOME/.asdf/shims:/opt/homebrew/bin:/usr/local/bin:/usr/bin:$PATH"` },
];

// Runs a shell snippet ON the target machine, reporting success + stdout. In prod
// this wraps `ssh target sh -c <script>` (or RemoteRunner.exec); tests inject a fake.
export type Probe = (script: string) => Promise<{ ok: boolean; stdout: string }>;

export interface DiscoverResult {
  ok: boolean;
  strategy?: string; // which rung resolved node
  version?: string; // `node -v` output, for the operator's log
}

/**
 * Find the first ladder rung that actually resolves a working node on the target.
 * A manual override (a user-supplied setup snippet) is tried first. Returns which
 * rung won + the node version, or ok:false when NOTHING works (never guesses).
 */
export async function discoverNode(probe: Probe, override?: string): Promise<DiscoverResult> {
  const rungs = override ? [{ name: "override", setup: override }, ...NODE_RUNGS] : NODE_RUNGS;
  for (const rung of rungs) {
    const script = `${rung.setup}\ncommand -v node >/dev/null 2>&1 && node -v`;
    const res = await probe(script);
    if (res.ok) return { ok: true, strategy: rung.name, version: res.stdout.trim() || undefined };
  }
  return { ok: false };
}

export interface WrapperOpts {
  appDir: string; // where the app (source + node_modules) lives on the target
  override?: string; // optional user-specified node setup, tried before the auto rungs
}

/** POSIX single-quote a string for embedding in the generated shell script. */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * The node-discovery ladder as a runnable shell snippet: each non-"path" rung is a
 * guarded fallback (only runs if node isn't found yet), override first. Shared by
 * the generated wrapper AND by bootstrap's `npm install` step, so install-time and
 * run-time resolve node identically.
 */
export function nodeLadderScript(override?: string): string {
  const auto = NODE_RUNGS.filter((r) => r.name !== "path");
  const rungs = override ? [{ name: "override", setup: override }, ...auto] : auto;
  return rungs.map((r) => `command -v node >/dev/null 2>&1 || { ${r.setup}; }`).join("\n");
}

/**
 * Generate the `tdsp` launcher for a target. It's self-discovering: every call it
 * walks the same ladder (override first, then fnm/nvm/common) until node resolves,
 * ensures git/tmux are on PATH, then execs the app passing args through. If no rung
 * works it exits 127 with a clear message instead of a cryptic command-not-found.
 */
export function renderWrapper(opts: WrapperOpts): string {
  const app = shq(opts.appDir);
  const ladder = nodeLadderScript(opts.override);
  return `#!/bin/sh
# tdsp launcher — generated by switchyard bootstrap. Finds a working node across
# heterogeneous machines (the non-interactive ssh PATH rarely has it), then runs
# the app. Self-discovering: retries the ladder each call, so it survives node
# version-manager changes without re-bootstrapping.
APP=${app}
${ladder}
# git/tmux for what the app actually does
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
command -v node >/dev/null 2>&1 || { echo "tdsp: no usable node found on this machine" >&2; exit 127; }
exec node "$APP/node_modules/.bin/tsx" "$APP/server/tdsp.ts" "$@"
`;
}

// ---------- one-time install orchestration ----------
// Injected ops so the sequence is testable without a real ssh: `run` executes a
// shell script on the target (via `ssh target sh -s`, stdin-fed — NOT nested
// quotes, which would let the remote shell eat `$(fnm env)`); `pushDir` streams a
// local dir over (tar-over-ssh).
export interface BootstrapDeps {
  appSrcDir: string; // local dir holding the app source to install (server/, web/, package.json, ...)
  home: string; // the target's home dir (absolute)
  run(script: string): Promise<{ ok: boolean; stdout: string }>;
  pushDir(localSrc: string, remoteDest: string): Promise<void>;
  override?: string; // optional manual node setup, tried first everywhere
}

export interface BootstrapResult {
  ok: boolean;
  appDir?: string;
  binPath?: string;
  strategy?: string;
  nodeVersion?: string;
  error?: string;
}

/**
 * Install tdsp onto a machine and return the verified wrapper path (which the
 * caller records as the host's tdsp_bin). Sequence, fail-fast at each gate:
 *   1. discover a working node — abort BEFORE touching the machine if none.
 *   2. push the app source to ~/.task-dispatcher/app.
 *   3. npm install there (same node ladder the wrapper will use).
 *   4. write the self-discovering wrapper to ~/.task-dispatcher/bin/tdsp, chmod +x.
 *   5. verify it actually runs (`tdsp list`) — a wrapper that doesn't run is a
 *      failed install, not a success.
 * Node is NEVER reinstalled — only the app's own node_modules.
 */
export async function bootstrapMachine(deps: BootstrapDeps): Promise<BootstrapResult> {
  const root = `${deps.home}/.task-dispatcher`;
  const appDir = `${root}/app`;
  const binPath = `${root}/bin/tdsp`;
  const ladder = nodeLadderScript(deps.override);

  // 1. discover node first — don't push anything to a machine we can't run on
  const found = await discoverNode(deps.run, deps.override);
  if (!found.ok) return { ok: false, error: "no usable node found on the target machine" };

  // 2. push source
  await deps.pushDir(deps.appSrcDir, appDir);

  // 3. install the app's own deps (native modules included), node via the ladder
  const inst = await deps.run(`${ladder}\ncd ${shq(appDir)} && npm install --no-audit --no-fund`);
  if (!inst.ok) return { ok: false, error: "npm install failed on the target" };

  // 4. write the self-discovering wrapper at a fixed path (base64 so its quotes/
  //    newlines survive the transport intact), make it executable
  const wrapper = renderWrapper({ appDir, override: deps.override });
  const b64 = Buffer.from(wrapper).toString("base64");
  const write = await deps.run(`mkdir -p ${shq(`${root}/bin`)} && printf %s ${shq(b64)} | base64 --decode > ${shq(binPath)} && chmod +x ${shq(binPath)} && echo OK`);
  if (!write.ok) return { ok: false, error: "could not install the wrapper" };

  // 5. verify the wrapper actually runs end to end (node → tsx → app → db)
  const verify = await deps.run(`${shq(binPath)} list >/dev/null 2>&1 && echo OK`);
  if (!verify.ok) return { ok: false, error: "the installed wrapper failed to run" };

  return { ok: true, appDir, binPath, strategy: found.strategy, nodeVersion: found.version };
}
