// Bootstrap a remote machine into a usable tdsp node WITHOUT assuming anything
// about how it provides node. `ssh host "cmd"` runs a non-interactive, non-login
// shell with a stripped environment, and machines vary wildly: nvm is a shell
// function that rc files often skip non-interactively, fnm/volta/asdf each
// initialize differently, others put node straight on PATH. So we DON'T assume —
// we empirically try a ladder of strategies until one actually resolves `node`,
// verify it, and generate a self-discovering wrapper that retries the same ladder
// at runtime (so it survives later version-manager drift). A manual override is
// always tried first, and an honest failure beats a silently-broken install.

// One rung of the discovery ladder: a name and the shell snippet that tries to
// make `node` available. The snippets are shared by discovery (verify a rung
// works now) and the generated wrapper (retry the rungs at runtime).
export interface NodeStrategy {
  name: string;
  setup: string;
}

export const NODE_RUNGS: NodeStrategy[] = [
  // already on the bare PATH (system / brew / volta shims often are) — empty setup
  { name: "path", setup: "" },
  // fnm: reachable as a binary even non-interactively (e.g. /opt/homebrew/bin/fnm)
  { name: "fnm", setup: `command -v fnm >/dev/null 2>&1 && { eval "$(fnm env 2>/dev/null)"; fnm use default >/dev/null 2>&1; }` },
  // nvm: source its script directly (the rc-guarded function won't load for us)
  { name: "nvm", setup: `[ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1` },
  // last resort: throw the usual shim/bin dirs onto PATH and hope one has node
  { name: "common", setup: `export PATH="$HOME/.volta/bin:$HOME/.asdf/shims:/opt/homebrew/bin:/usr/local/bin:/usr/bin:$PATH"` },
];

// Runs a shell snippet ON the target machine, reporting success + stdout. In prod
// this wraps `ssh target sh -c <script>` (or RemoteRunner.exec); tests inject a fake.
export type Probe = (script: string) => Promise<{ ok: boolean; stdout: string }>;

export interface DiscoverResult {
  ok: boolean;
  strategy?: string; // which rung resolved node
  version?: string; // `node -v` output, for the operator's log
}

/**
 * Find the first ladder rung that actually resolves a working node on the target.
 * A manual override (a user-supplied setup snippet) is tried first. Returns which
 * rung won + the node version, or ok:false when NOTHING works (never guesses).
 */
export async function discoverNode(probe: Probe, override?: string): Promise<DiscoverResult> {
  const rungs = override ? [{ name: "override", setup: override }, ...NODE_RUNGS] : NODE_RUNGS;
  for (const rung of rungs) {
    const script = `${rung.setup}\ncommand -v node >/dev/null 2>&1 && node -v`;
    const res = await probe(script);
    if (res.ok) return { ok: true, strategy: rung.name, version: res.stdout.trim() || undefined };
  }
  return { ok: false };
}

export interface WrapperOpts {
  appDir: string; // where the app (source + node_modules) lives on the target
  override?: string; // optional user-specified node setup, tried before the auto rungs
}

/** POSIX single-quote a string for embedding in the generated shell script. */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Generate the `tdsp` launcher for a target. It's self-discovering: every call it
 * walks the same ladder (override first, then fnm/nvm/common) until node resolves,
 * ensures git/tmux are on PATH, then execs the app passing args through. If no rung
 * works it exits 127 with a clear message instead of a cryptic command-not-found.
 */
export function renderWrapper(opts: WrapperOpts): string {
  const app = shq(opts.appDir);
  // each non-"path" rung becomes a guarded fallback: only run if node isn't found yet
  const auto = NODE_RUNGS.filter((r) => r.name !== "path");
  const rungs = opts.override ? [{ name: "override", setup: opts.override }, ...auto] : auto;
  const ladder = rungs
    .map((r) => `command -v node >/dev/null 2>&1 || { ${r.setup}; }`)
    .join("\n");
  return `#!/bin/sh
# tdsp launcher — generated by switchyard bootstrap. Finds a working node across
# heterogeneous machines (the non-interactive ssh PATH rarely has it), then runs
# the app. Self-discovering: retries the ladder each call, so it survives node
# version-manager changes without re-bootstrapping.
APP=${app}
${ladder}
# git/tmux for what the app actually does
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
command -v node >/dev/null 2>&1 || { echo "tdsp: no usable node found on this machine" >&2; exit 127; }
exec node "$APP/node_modules/.bin/tsx" "$APP/server/tdsp.ts" "$@"
`;
}
